### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ayako-k2** [ayako-kiyonari/furima-41791#21]
#URL
https://furima-41791.onrender.com/

**Comment by TakashiKozuma** [comment]
挙動確認依頼ありがとうございます。
現状だと挙動の確認ができなかったため、Basic認証のユーザー名とパスワードも送付していただくことは可能でしょうか？

お手数ですが、Basic認証のユーザー名とパスワードを送付していただき、再度挙動確認依頼のフォームの提出をお願いいたします。

**Comment by ayako-k2** [comment]
Basic認証ユーザー名: admin 
                パスワード:2222
です。よろしくお願いいたします。

ちなみに挙動の確認ができないというのは、ユーザー名かパスワードが間違っていてアプリに入ることができないという意味でしょうか？18時前にユーザーが作成され、出品された形跡があったので、どう挙動の確認ができないのか気になりまして。。。

**Comment by motomuun** [comment]
再度ご提出頂きありがとうございます。

昨日の挙動確認について、大変失礼いたしました。
こちらの確認不足で、挙動確認依頼フォームに正しいユーザー名とパスワードを記載頂いたにも関わらず、
再度お伺いしてしまった次第です。

18時前のユーザー作成と出品の挙動は、挙動確認の自動チェックツールが動作した形跡でございます。
挙動確認は自動チェックツールと手動チェックの両方を用いて確認を行っております。

こちらの確認不足でお手数をおかけしたこと、挙動確認をお待たせしてしまったこと、深くお詫び申し上げます。


動作の確認をしたところ、1点だけ修正していただきたい箇所がございました。
以下のご確認をお願いします。

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
初期値が「--」になっています。細かい点ですが、要件と揃うように「---」に修正しましょう。
<img width="659" alt="スクリーンショット 2024-12-18 9 18 13" src="https://github.com/user-attachments/assets/8df1a231-571c-402e-950f-82de87505009" />


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ayako-k2** [comment]
ご確認いただきまたご説明いただきありがとうございました。
再度本番環境での確認完了いたしました。
今回は出品時、購入時画面の修正なので、データベースのリセットは行っていません。
よろしくお願いいたします。

**Comment by motomuun** [comment]
再度ご提出頂きありがとうございます。
最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
